---
settings:
  parallel: true

driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  nodes_path: 'test/integration/nodes'
  data_bags_path: 'test/integration/data_bags'
  environments_path: 'test/integration/environments'
  roles_path: 'test/integration/roles'
  require_chef_omnibus: 12

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_plugin: docker
    driver:
      image: ernestasposkus/centos7
      run_command: '/usr/lib/systemd/systemd'
      run_options: '--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: centos-6
    driver_plugin: docker
    driver:
      image: ernestasposkus/centos6
      run_command: '/sbin/init'
      run_options: ''
    verifier:
      attributes:
        service: upstart
  - name: ubuntu-1604
    driver_plugin: docker
    driver:
      image: ernestasposkus/ubuntu1604
      run_command: '/lib/systemd/systemd'
      run_options: '--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: ubuntu-1404
    driver_plugin: docker
    driver:
      image: ubuntu-upstart:14.04
      disable_upstart: false
      run_command: '/sbin/init'
      run_options: ''
      provision_command: service ssh start
    verifier:
      attributes:
        service: upstart

suites:
  - name: default
    run_list:
      - recipe[test-proxysql::default]
      - role[admin_variables]
      - role[mysql_variables]
      - role[mysql_servers]
      - role[mysql_users]
      - role[mysql_query_rules]
      - role[mysql_replication_hostgroups]
    attributes:
      proxysql:
        lock_version: false

  - name: 2mysql
    run_list:
      - recipe[test-proxysql::2mysql]
    attributes:
      proxysql:
        lock_version: false
